-- CreateEnum
CREATE TYPE "ProgramCategory" AS ENUM ('BODYBUILDING', 'STRENGTH_TRAINING', 'FAT_LOSS', 'ATHLETIC_PERFORMANCE', 'REHAB', 'FOOTBALL_FITNESS');

-- AlterTable
ALTER TABLE "Program" ADD COLUMN     "category" "ProgramCategory" NOT NULL DEFAULT 'STRENGTH_TRAINING';
